name: CI/CD Pipeline

permissions:
  actions: read
  contents: read
  security-events: write

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]  # Trigger deployment only for tags starting with 'v'
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '41 7 * * 6'  # Run every Saturday at 7:41 UTC

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsnappy-dev
          pip install -r requirements-test.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run tests and generate coverage report
        run: |
          pytest --maxfail=0 --disable-warnings --tb=short --cov=. --cov-report=xml:coverage.xml

  codeql:
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        include:
        - language: python
          build-mode: none
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"

  sonarqube:
    needs: test  # Need the test job to succeed
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          extraProperties: |
            sonar.python.coverage.reportPaths=coverage.xml

  deploy:
    needs: [test, codeql, sonarqube]  # Need all previous jobs to succeed
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/deploy-job.yml
    secrets: inherit
    with:
      docker_tag: latest
